# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Absinthe' do
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.1'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'ReactorKit'
  pod 'Then'
  pod 'Kingfisher', '~> 5.0'

end
